# Generated by Django 3.2.4 on 2021-07-03 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=224, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo')),
                ('logo_url', models.TextField(blank=True, null=True)),
                ('enable', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='batch',
            name='Friday',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='Friday_time',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='Monday',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='Monday_time',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='Saturday',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='Saturday_time',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='Sunday',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='Sunday_time',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='Thursday',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='Thursday_time',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='Tuesday',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='Tuesday_time',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='Wednesday',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='Wednesday_time',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='join_url',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='start_url',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='zoom_meeting_id',
        ),
        migrations.AddField(
            model_name='batch',
            name='batch_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='batch_name',
            field=models.CharField(blank=True, max_length=224, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='number_of_week',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='online_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='room_expires',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='room_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='room_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='timing',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(blank=True, max_length=224, null=True)),
                ('enable', models.BooleanField(default=True)),
                ('category_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('available_date', models.DateTimeField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('appendix', models.TextField(blank=True, null=True)),
                ('course_type', models.CharField(blank=True, max_length=100, null=True)),
                ('course_description', models.TextField(blank=True, null=True)),
                ('learning_goals', models.TextField(blank=True, null=True)),
                ('home_work', models.TextField(blank=True, null=True)),
                ('assginment', models.TextField(blank=True, null=True)),
                ('parental_guidence', models.TextField(blank=True, null=True)),
                ('assesstment', models.TextField(blank=True, null=True)),
                ('sources', models.TextField(blank=True, null=True)),
                ('course_price', models.IntegerField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('max_students', models.IntegerField(blank=True, null=True)),
                ('min_students', models.IntegerField(blank=True, null=True)),
                ('min_age', models.IntegerField(blank=True, null=True)),
                ('max_age', models.IntegerField(blank=True, null=True)),
                ('number_of_classes_week', models.IntegerField(blank=True, null=True)),
                ('number_of_week', models.IntegerField(blank=True, null=True)),
                ('total_classes', models.IntegerField(blank=True, null=True)),
                ('time_hour', models.CharField(blank=True, max_length=100, null=True)),
                ('time_minute', models.CharField(blank=True, max_length=100, null=True)),
                ('outside_work', models.CharField(blank=True, max_length=224, null=True)),
                ('material', models.BooleanField(default=False)),
                ('is_online', models.BooleanField(default=False)),
                ('welcome_post', models.TextField(blank=True, null=True)),
                ('course_video', models.FileField(blank=True, null=True, upload_to='course_videos')),
                ('course_video_url', models.TextField(blank=True, null=True)),
                ('course_logo_url', models.TextField(blank=True, null=True)),
                ('approved_by_admin', models.BooleanField(default=False)),
                ('rejected_by_admin', models.BooleanField(default=False)),
                ('language_of_instruction', models.TextField(blank=True, null=True)),
                ('refund', models.TextField(blank=True, null=True)),
                ('category_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.category')),
                ('sub_category_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.subcategory')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='course_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.course'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='course_name',
            field=models.ManyToManyField(blank=True, to='api.Course'),
        ),
    ]
