# Generated by Django 3.2.4 on 2021-07-03 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210703_1622'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
