# Generated by Django 3.2.4 on 2021-06-21 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_meeting_cancel_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='subjct_id',
            new_name='subject_id',
        ),
    ]
