# Generated by Django 3.2.4 on 2021-06-21 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_subjct_id_meeting_subject_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='licence_id',
            new_name='licence',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='subject_id',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='teacher_id',
            new_name='teacher',
        ),
    ]
