# Generated by Django 3.2.4 on 2021-07-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='zoom_user_id',
            field=models.TextField(blank=True, default='NA', null=True),
        ),
    ]
