# Generated by Django 3.2.4 on 2021-07-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customuser_zoom_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='join_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
