# Generated by Django 3.2.4 on 2021-06-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210621_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date_created',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
