# Generated by Django 3.2.4 on 2021-06-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210621_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='licence',
            name='client_id',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='licence',
            name='client_secret',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='licence',
            name='installation_url',
            field=models.TextField(default='NA'),
        ),
        migrations.AlterField(
            model_name='licence',
            name='license_no',
            field=models.EmailField(max_length=254),
        ),
    ]
