# Generated by Django 3.2.4 on 2021-06-21 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210621_2353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='date_created',
            new_name='meeting_date',
        ),
    ]
