# Generated by Django 3.2.4 on 2021-06-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_date_created_meeting_meeting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='licence',
            name='access_token',
            field=models.TextField(default='NA'),
        ),
    ]
