# Generated by Django 3.2.4 on 2021-06-26 20:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_licence_access_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(default=datetime.date.today)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('duration', models.IntegerField()),
                ('Sunday', models.BooleanField(default=False)),
                ('Sunday_time', models.TimeField()),
                ('Monday', models.BooleanField(default=False)),
                ('Monday_time', models.TimeField()),
                ('Tuesday', models.BooleanField(default=False)),
                ('Tuesday_time', models.TimeField()),
                ('Wednesday', models.BooleanField(default=False)),
                ('Wednesday_time', models.TimeField()),
                ('Thursday', models.BooleanField(default=False)),
                ('Thursday_time', models.TimeField()),
                ('Friday', models.BooleanField(default=False)),
                ('Friday_time', models.TimeField()),
                ('Saturday', models.BooleanField(default=False)),
                ('Saturday_time', models.TimeField()),
                ('start_url', models.TextField(default='NA')),
                ('join_url', models.TextField(default='NA')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.teacher')),
            ],
        ),
    ]
