# Generated by Django 3.2.4 on 2021-06-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='Friday_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='Monday_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='Saturday_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='Sunday_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='Thursday_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='Tuesday_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='Wednesday_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
