# Generated by Django 3.2.4 on 2021-06-27 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_licence_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='licence',
            old_name='access_token',
            new_name='refresh_token',
        ),
    ]
