# Generated by Django 3.2.4 on 2021-06-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_access_token_licence_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='zoom_user_id',
            field=models.TextField(default='NA'),
        ),
    ]
