# Generated by Django 3.2.4 on 2021-06-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_teacher_zoom_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(default='NA', max_length=50),
            preserve_default=False,
        ),
    ]
