# Generated by Django 3.2.4 on 2021-06-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210627_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='zoom_meeting_id',
            field=models.TextField(default='NA'),
        ),
    ]
