# Generated by Django 3.2.4 on 2021-07-02 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_batch_zoom_meeting_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='licence',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Date',
        ),
        migrations.DeleteModel(
            name='Meeting',
        ),
    ]
