# Generated by Django 3.2.4 on 2021-07-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20210702_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licence',
            name='status',
        ),
        migrations.AddField(
            model_name='licence',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
